### ISSUE TITLE
Problem with opening parentheses

### ISSUE THREAD

**Issue by halilim** [sbagdat/turkish_support#5]
```ruby
'LOREM ( IPSUM)'.titleize
```

```log
/Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/helpers.rb:28:in `prepare_for': Invalid arguments for method `prepare_for`! (ArgumentError)
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/helpers.rb:67:in `prepare_for_capitalize'
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/helpers.rb:31:in `call'
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/helpers.rb:31:in `prepare_for'
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/string_methods.rb:19:in `block (3 levels) in <module:TurkishSupport>'
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/string_methods.rb:30:in `block in titleize'
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/string_methods.rb:25:in `map'
	from /Users/halil/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turkish_support-1.0.0/lib/turkish_support/string_methods.rb:25:in `titleize'
	from test.rb:9:in `hey'
	from test.rb:13:in `<main>'
```

```ruby
'( '.titleize # => <The same error>
'('.titleize # => <The same error>
'LOREM (IPSUM)'.titleize # => Lorem (Ipsum)
```

**Comment by sbagdat** [comment]
@halilim Thanks for reporting :heart:
